language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '10'
  - '12'
  - '14'

before_script:
  - npm prune

after_success:
  - npm install
  - npm run build
  - npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
